<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN"
 "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" >
<xliff version="1.0" xml:lang="en">
 <file datatype="plaintext" original="842" source-language="EN">
  <header></header>
  <body>
<trans-unit id="001" resname="TRANSLATION_TITLE">
<source>Preloader</source>
</trans-unit>
<trans-unit id="002" resname="IDS_PRELOADER_LOADING_GAME">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20face%20%3D%20%27jokerman_fnt%27%20size%20%3D%20%2770%27%3ELoading%20Game%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="003" resname="IDS_PRELOADER_LOADING_BAND">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20face%20%3D%20%27jokerman_fnt%27%20size%20%3D%20%2770%27%3ELoading%20Band%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="004" resname="IDS_PRELOADER_PLUGIN">
<source>%3Cfont%20face%20%3D%20%27customFSS_fnt%27%20size%20%3D%20%2740%27%3EPlug-in%20Version%3A%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="005" resname="IDS_PRELOADER_LOADED">
<source>%3Cfont%20face%20%3D%20%27customFSS_fnt%27%20size%20%3D%20%2740%27%3ELoaded%3A%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="006" resname="IDS_PRELOADER_ELAPSED">
<source>%3Cfont%20face%20%3D%20%27customFSS_fnt%27%20size%20%3D%20%2740%27%3EElapsed%20Time%3A%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="007" resname="IDS_PRELOADER_ESTIMATED">
<source>%3Cfont%20face%20%3D%20%27customFSS_fnt%27%20size%20%3D%20%2740%27%3EEstimated%20Time%3A%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="008" resname="IDS_PRELOADER_RATE">
<source>%3Cfont%20face%20%3D%20%27customFSS_fnt%27%20size%20%3D%20%2740%27%3ERate%3A%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="009" resname="IDS_PRELOADER_PERCENT">
<source>%3Cfont%20face%20%3D%20%27customFSS_fnt%27%20size%20%3D%20%2740%27%3E%25%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="010" resname="IDS_PRELOADER_K">
<source>%3Cfont%20face%20%3D%20%27customFSS_fnt%27%20size%20%3D%20%2740%27%3Ek%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="011" resname="IDS_PRELOADER_SEC">
<source>%3Cfont%20face%20%3D%20%27customFSS_fnt%27%20size%20%3D%20%2740%27%3Esec.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="012" resname="IDS_PRELOADER_KPS">
<source>%3Cfont%20face%20%3D%20%27customFSS_fnt%27%20size%20%3D%20%2740%27%3Ekps%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="013" resname="IDS_PRELOADER_ADVERT">
<source>%3Cp%20align%3D%27left%27%3E%3Cfont%20size%3D%2718%27%3EADVERTISEMENT%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="014" resname="IDS_PRELOADER_FEATURED">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%3D%2728%27%3EFeatured%20Game%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="015" resname="IDS_PRELOADER_SPONSORED">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%3D%2728%27%3ESPONSORED%20BY%3A%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="016" resname="IDS_PRELOADER_FEATURED2">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%3D%2728%27%3EThis%20Featured%20Game%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="017" resname="IDS_PRELOADER_SPONSORED2">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%3D%2728%27%3EIS%20BROUGHT%20TO%20YOU%20BY%3A%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="018" resname="IDS_PRELOADER_NOTLOGGEDIN">
<source>You%27re%20not%20logged%20in%21%20Choose%20an%20option%3A</source>
</trans-unit>
<trans-unit id="019" resname="IDS_PRELOADER_PLAYGAME">
<source>%3CA%20HREF%3D%27asfunction%3A_root.HTMLClick%2C1%27%3EPlay%20Game%3C%2FA%3E</source>
</trans-unit>
<trans-unit id="020" resname="IDS_PRELOADER_SIGNUP">
<source>%3CA%20HREF%3D%27asfunction%3A_root.HTMLClick%2C2%27%3ESign%20Up%3C%2FA%3E</source>
</trans-unit>
<trans-unit id="021" resname="IDS_PRELOADER_LOGIN">
<source>%3CA%20HREF%3D%27asfunction%3A_root.HTMLClick%2C3%27%3ELogin%3C%2FA%3E</source>
</trans-unit>
<trans-unit id="022" resname="IDS_PRELOADER_SIGNUP_ONLY">
<source>Sign%20Up</source>
</trans-unit>
<trans-unit id="023" resname="IDS_PRELOADER_LOGIN_ONLY">
<source>Login</source>
</trans-unit>
<trans-unit id="024" resname="IDS_SM_TAG1_OPEN">
<source>%3Cp%20align%3D%27center%27%3E</source>
</trans-unit>
<trans-unit id="025" resname="IDS_SM_TAG2_OPEN">
<source>%3Cp%20align%3D%27center%27%3E</source>
</trans-unit>
<trans-unit id="026" resname="IDS_SM_TAG3_OPEN">
<source>%3Cp%20align%3D%27center%27%3E</source>
</trans-unit>
<trans-unit id="027" resname="IDS_SM_TAG_CLOSE">
<source>%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="028" resname="IDS_SM_score">
<source>Score%3A</source>
</trans-unit>
<trans-unit id="029" resname="IDS_SM_npscore">
<source>NP%3A</source>
</trans-unit>
<trans-unit id="030" resname="IDS_SM_pending">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3E%3Cbr%3ESuccess%20Pending</source>
</trans-unit>
<trans-unit id="031" resname="IDS_SM_success">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3ESuccess%21%20Your%20NP%3A</source>
</trans-unit>
<trans-unit id="032" resname="IDS_SM_bonus">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3Ex2%20Bonus%21%20Your%20NP%3A</source>
</trans-unit>
<trans-unit id="033" resname="IDS_SM_hiscore">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3EYour%20High%20Score%3A</source>
</trans-unit>
<trans-unit id="034" resname="IDS_SM_plays">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3EPlays%20Today%3A</source>
</trans-unit>
<trans-unit id="035" resname="IDS_SM_restart">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffffff%27%3E%3CA%20HREF%3D%27asfunction%3A_parent._parent.restartGame%27%3E%3Cu%3ERestart%20Game%3C%2Fu%3E%3C%2Fa%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="036" resname="IDS_SM_tryagain">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffffff%27%3E%3CA%20HREF%3D%27asfunction%3A_parent._parent.resendScore%27%3E%3Cu%3ETry%20Again%3C%2Fu%3E%3C%2Fa%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="037" resname="IDS_SM_restart_new">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffffff%27%3E%3CA%20HREF%3D%27asfunction%3A_parent._parent.restartGame%27%3E%3Cu%3ERestart%20Game%3C%2Fu%3E%3C%2Fa%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="038" resname="IDS_SM_challengecard">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffffff%27%3E%3CA%20HREF%3D%27asfunction%3A_parent._parent.showCard%27%3E%3Cu%3ESend%20a%20Challenge%20Card%3C%2Fu%3E%3C%2Fa%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="039" resname="IDS_SM_anothercard">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffffff%27%3E%3CA%20HREF%3D%27asfunction%3A_parent._parent.showCard%27%3E%3Cu%3ESend%20another%20Card%3C%2Fu%3E%3C%2Fa%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="040" resname="IDS_SM_sendacard">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffffff%27%3ESend%20a%20Challenge%20Card%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="041" resname="IDS_SM_submitcard">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffffff%27%3E%3CA%20HREF%3D%27asfunction%3A_parent._parent.submitCard%27%3E%3Cu%3ESubmit%3C%2Fu%3E%3C%2Fa%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="042" resname="IDS_SM_cancelcard">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffffff%27%3E%3CA%20HREF%3D%27asfunction%3A_parent._parent.cancelCard%27%3E%3Cu%3ECancel%3C%2Fu%3E%3C%2Fa%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="043" resname="IDS_SM_cardreturn">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffffff%27%3E%3CA%20HREF%3D%27asfunction%3A_parent._parent.backToCard%27%3E%3Cu%3EBack%3C%2Fu%3E%3C%2Fa%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="044" resname="IDS_SM_mainreturn">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffffff%27%3E%3CA%20HREF%3D%27asfunction%3A_parent._parent.cancelCard%27%3E%3Cu%3EI%27m%20done%3C%2Fu%3E%3C%2Fa%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="045" resname="IDS_SM_preparecard">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffffff%27%3E%3Cbr%3EPreparing%20email%20form...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="046" resname="IDS_SM_sendingcard">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffffff%27%3E%3Cbr%3ESending%20Card...%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="047" resname="IDS_SM_CCARD_NAME1">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2712%27%20color%3D%27%23ffff00%27%3EYour%20First%20Name%3A%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="048" resname="IDS_SM_CCARD_EMAIL1">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2712%27%20color%3D%27%23ffff00%27%3EYour%20Email%20Address%3A%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="049" resname="IDS_SM_CCARD_NAME2">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2712%27%20color%3D%27%23ffff00%27%3EFriend%27s%20First%20Name%3A%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="050" resname="IDS_SM_CCARD_EMAIL2">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2712%27%20color%3D%27%23ffff00%27%3EFriend%27s%20Email%3A%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="051" resname="IDS_FGS_PRESS_ANY_KEY">
<source>Press%20Any%20Key%20To%20Continue</source>
</trans-unit>
<trans-unit id="052" resname="FGS_MAIN_MENU_START_GAME">
<source>Start%20Game</source>
</trans-unit>
<trans-unit id="053" resname="FGS_MAIN_MENU_VIEW_INSTRUCTIONS">
<source>View%20Instructions</source>
</trans-unit>
<trans-unit id="054" resname="FGS_MAIN_MENU_VISIT_WEBSITE">
<source>Visit%20Website</source>
</trans-unit>
<trans-unit id="055" resname="FGS_MAIN_MENU_VIEW_TRAILER">
<source>View%20Trailer</source>
</trans-unit>
<trans-unit id="056" resname="FGS_MAIN_MENU_TURN_MUSIC_OFF">
<source>Turn%20Music%20Off</source>
</trans-unit>
<trans-unit id="057" resname="FGS_MAIN_MENU_TURN_SOUND_OFF">
<source>Turn%20Sound%20Off</source>
</trans-unit>
<trans-unit id="058" resname="FGS_MAIN_MENU_TURN_MUSIC_ON">
<source>Turn%20Music%20On</source>
</trans-unit>
<trans-unit id="059" resname="FGS_MAIN_MENU_TURN_SOUND_ON">
<source>Turn%20Sound%20On</source>
</trans-unit>
<trans-unit id="060" resname="FGS_MAIN_MENU_SETUP">
<source>Setup</source>
</trans-unit>
<trans-unit id="061" resname="FGS_GAME_MENU_END_GAME">
<source>End%20Game</source>
</trans-unit>
<trans-unit id="062" resname="FGS_OTHER_MENU_GO_BACK">
<source>Go%20Back</source>
</trans-unit>
<trans-unit id="063" resname="FGS_OTHER_MENU_MORE">
<source>More</source>
</trans-unit>
<trans-unit id="064" resname="FGS_GAME_OVER_MENU_RESTART_GAME">
<source>Restart%20Game</source>
</trans-unit>
<trans-unit id="065" resname="FGS_GAME_OVER_MENU_SEND_SCORE">
<source>Send%20Score</source>
</trans-unit>
<trans-unit id="066" resname="IDS_SM_ERR_MAXPLAYS">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2712%27%20color%3D%27%23ff0000%27%3EYou%20have%20already%20reached%20the%20maximum%20number%20of%20times%20you%20can%20post%20your%20score%20for%20today%21%20Play%20again%20tomorrow%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="067" resname="IDS_SM_ERR_ZEROSCORE">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3EYou%20didn%27t%20score%20any%20points%2C%20so%20your%20score%20cannot%20be%20posted%20-%20sorry%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="068" resname="IDS_SM_ERR_UNKNOWN">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3ESorry%2C%20our%20servers%20are%20currently%20experiencing%20problems%20and%20we%20cannot%20accept%20your%20score%20right%20now%20%3A%28%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="069" resname="IDS_SM_ERR_INVALID">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3ESorry%2C%20but%20you%20cannot%20send%20scores%20if%20you%20have%20not%20%3CA%20HREF%3D%27asfunction%3A_parent._parent.validateEmail%27%3E%3Cu%3Evalidated%20your%20account%3C%2Fu%3E%3C%2Fa%3E%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="070" resname="IDS_SM_ERR_TIMEOUT">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3ESorry%2C%20but%20there%20is%20no%20response%20from%20the%20server%20at%20this%20time%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="071" resname="IDS_SM_ERR_NOLOGIN">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3EPlease%20%3CA%20HREF%3D%27asfunction%3A_parent._parent.showLogin%27%3E%3Cu%3ELog%20In%3C%2Fu%3E%3C%2Fa%3E%20to%20Neopets%20to%20submit%20your%20next%20score%20or%20%3CA%20HREF%3D%27asfunction%3A_parent._parent.showLogin%27%3E%3Cu%3ESign%20Up%20Today%3C%2Fu%3E%3C%2Fa%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="072" resname="IDS_SM_ERR_COOKIE">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3EProblem%20reading%20your%20cookies.%20Please%20log%20out%20and%20log%20back%20in.%20Thanks.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="073" resname="IDS_SM_ERR_CHALLENGE">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3EChallenge%20posted%2C%20however%2C%20max%20scores%20already%20posted%20for%20today.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="074" resname="IDS_SM_ERR_NOCHALL">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3EYou%20have%20no%20outstanding%20challenges%20for%20this%20game%20and%20you%20have%20already%20posted%20your%20max%20scores%20for%20today.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="075" resname="IDS_SM_ERR_CHALLSLOW">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3E%28Scroll%20Down%29%20Sorry%2C%20but%20your%20computer%20is%20running%20too%20slow%20to%20be%20in%20a%20challenge.%20%20This%20would%20make%20the%20game%20unfair%20to%20other%20users%20that%20play%20the%20game%20at%20regular%20speed.%20%20To%20speed%20your%20computer%20up%2C%20play%20the%20game%20with%20the%20smallest%20window%20setting%20and%20close%20all%20other%20applications%20or%20browser%20windows%20while%20you%20play%20the%20game.%20%20If%20that%20does%20not%20work%2C%20you%20may%20withdraw%20from%20a%20challenge%20to%20avoid%20this%20message%20%3CA%20HREF%3D%27asfunction%3A_parent._parent.showChallenge%27%3E%3Cu%3Ehere%3C%2Fu%3E%3C%2Fa%3E.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="076" resname="IDS_SM_ERR_DC_COMP">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3E%28Scroll%20Down%29.%20Sorry%2C%20but%20your%20computer%20is%20running%20too%20slow%20for%20this%20score%20to%20be%20valid%20for%20the%20Daily%20Competition.%20%20This%20would%20make%20the%20game%20unfair%20to%20other%20users%20that%20play%20the%20game%20at%20regular%20speed.%20%20To%20speed%20your%20computer%20up%2C%20play%20the%20game%20with%20the%20smallest%20window%20setting%20and%20close%20all%20other%20applications%20or%20browser%20windows.%20%20Once%20you%20do%20that%2C%20you%20may%20re-enter%20the%20Daily%20Competition.%20%20You%20may%20also%20withdraw%20from%20the%20Daily%20Competition%20on%20the%20Daily%20Competition%20page.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="077" resname="IDS_SM_ERR_DC_TIME">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3ESorry%2C%20but%20you%20did%20not%20get%20your%20score%20sent%20in%20in%20time%20to%20count%20towards%20the%20Daily%20Competition%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="078" resname="IDS_SM_ERR_REVIEW">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3E%28Scroll%20Down%29%20Your%20score%20is%20being%20reviewed%20by%20staff.%20If%20it%20is%20deemed%20valid%2C%20you%20will%20receive%20your%20Neopoints%20and%20go%20into%20the%20hiscore%20table.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="079" resname="IDS_SM_ERR_QUICK_SESSION">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3E%28Scroll%20Down%29%20Your%20game%20play%20was%20too%20short%20to%20be%20counted.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="080" resname="IDS_SM_ERR_MISSING_HASH">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3EProblems%20processing%20your%20score.%20For%20best%20results%2C%20close%20the%20pop%20up%20window%20and%20re-open%20it%20to%20restart%20your%20game.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="081" resname="IDS_MESSAGE_1">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3ESorry%2C%20but%20your%20score%20is%20too%20low%20to%20be%20entered%20into%20the%20World%20Challenge.%20%28Scroll%20down%29.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="082" resname="IDS_SM_ERR_WC_TOO_LOW">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ff0000%27%3ESorry%2C%20but%20your%20score%20is%20too%20low%20to%20be%20entered%20into%20the%20World%20Challenge%20and%20you%20have%20posted%20your%20max%20scores%20for%20the%20day.%20The%20minimum%20score%20required%20varies%20slightly%20from%20challenge%20to%20challenge%20and%20throughout%20the%20hour.%20%20To%20ensure%20your%20score%20is%20entered%2C%20play%20the%20best%20game%20you%20can.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="083" resname="IDS_SM_DD_MAX">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3EYou%27ve%20sent%20your%20score%20for%20Neopoints%20the%20maximum%20number%20of%20times%20today%20for%20this%20game.%20You%20may%2C%20however%2C%20keep%20submitting%20scores%20to%20try%20to%20beat%20AAA%20or%20Abigail%2C%20although%20you%20won%27t%20receive%20Neopoints%20for%20doing%20so.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="084" resname="IDS_SM_DD_BEAT_AAA">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3ECongratulations%21%20%20You%27ve%20beaten%20AAA.%20%20Go%20get%20your%20prize%20and%20play%20more%20Daily%20Dare%20games.%20%20Don%27t%20forget%20to%20take%20the%20%3Ca%20href%3D%27%2Fgames%2Faaa%2Fnc_challenge.phtml%27%20target%3D%27_blank%27%3ENC%20Challenge%3C%2Fa%3E%20for%20a%20chance%20to%20win%20additional%20prizes%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="085" resname="IDS_SM_DD_BEAT_ABIGAIL">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3ECongratulations%21%20%20You%27ve%20beaten%20Abigail.%20%20Go%20get%20your%20prize%20and%20play%20more%20Daily%20Dare%20games.%20%20Don%27t%20forget%20to%20take%20the%20%3Ca%20href%3D%27%2Fgames%2Faaa%2Fnc_challenge.phtml%27%20target%3D%27_blank%27%3ENC%20Challenge%3C%2Fa%3E%20for%20a%20chance%20to%20win%20additional%20prizes%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="086" resname="IDS_SM_DD_BEAT_DOUBLE">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3ECongratulations%21%20%20You%27ve%20won%20the%20Double%20Dare.%20%20Go%20get%20your%20prize%20and%20play%20more%20Daily%20Dare%20games.%20%20Don%27t%20forget%20to%20take%20the%20%3Ca%20href%3D%27%2Fgames%2Faaa%2Fnc_challenge.phtml%27%20target%3D%27_blank%27%3ENC%20Challenge%3C%2Fa%3E%20for%20a%20chance%20to%20win%20additional%20prizes%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="087" resname="IDS_SM_DD_BEAT_LULU">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3ECongratulations%21%20%20You%27ve%20beaten%20Lulu.%20%20Go%20get%20your%20prize%20and%20play%20more%20NC%20Challenge%20games.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="088" resname="IDS_SM_DD_NC_BEAT_LULU">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3ECongratulations%21%20You%20have%20beaten%20or%20matched%20Lulu%27s%20score%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="089" resname="IDS_SM_DD_NC_LOST_LULU">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3EYou%20have%20not%20beaten%20or%20matched%20Lulu%27s%20score%21%20Try%20again%21%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="090" resname="IDS_SM_AC_MAX_SCORE">
<source>%3Cfont%20face%3D%27customFSS_fnt%27%20size%3D%2714%27%20color%3D%27%23ffff00%27%3EYou%27ve%20sent%20your%20score%20for%20Neopoints%20the%20maximum%20number%20of%20times%20today%20for%20this%20game.%20%20You%20may%20keep%20submitting%20scores%20to%20advance%20your%20team%20and%20earn%20prize%20shop%20points.%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="091" resname="IDS_CARD_PREPARING_EMAIL_FORM">
<source>Preparing%20email%20form.</source>
</trans-unit>
<trans-unit id="092" resname="IDS_CARD_PLEASE_COMPLETE_THE_FORM">
<source>Please%20complete%20the%20form.</source>
</trans-unit>
<trans-unit id="093" resname="IDS_CARD_VALIDATING_FORM">
<source>Validating%20Form.</source>
</trans-unit>
<trans-unit id="094" resname="IDS_CARD_SENDING_FORM">
<source>Sending%20Form.</source>
</trans-unit>
<trans-unit id="095" resname="IDS_CARD_UNDERAGE_SENDER_NAME">
<source>A%20Neopets.com%20User</source>
</trans-unit>
<trans-unit id="096" resname="IDS_CARD_UNDERAGE_SENDER_EMAIL">
<source>support%40neopets.com</source>
</trans-unit>
<trans-unit id="097" resname="IDS_CARD_UNDERAGE_RECIPIENT_NAME">
<source>A%20Friend%20of%20Neopets.com</source>
</trans-unit>
<trans-unit id="098" resname="IDS_CARD_PLEASE_COMPLETE_AND_SUBMIT_FORM">
<source>Please%20complete%20and%20submit%20form.</source>
</trans-unit>
<trans-unit id="099" resname="IDS_CARD_YOUR_FIRST_NAME">
<source>%3CP%20ALIGN%3D%22LEFT%22%3EYour%20First%20Name%3A%3C%2FP%3E</source>
</trans-unit>
<trans-unit id="100" resname="IDS_CARD_YOUR_EMAIL_ADDRESS">
<source>%3CP%20ALIGN%3D%22LEFT%22%3EYour%20Email%20Address%3A%3C%2FP%3E</source>
</trans-unit>
<trans-unit id="101" resname="IDS_CARD_FRIENDS_FIRST_NAME">
<source>%3CP%20ALIGN%3D%22LEFT%22%3EFriend%27s%20First%20Name%3A%3C%2FP%3E</source>
</trans-unit>
<trans-unit id="102" resname="IDS_CARD_FRIENDS_EMAIL_ADDRESS">
<source>%3CP%20ALIGN%3D%22LEFT%22%3EFriend%27s%20Email%3A%3C%2FP%3E</source>
</trans-unit>
<trans-unit id="103" resname="IDS_CARD_TITLE">
<source>Postcard%0APrinted%20in%20Neopia</source>
</trans-unit>
<trans-unit id="104" resname="IDS_CARD_SUBMIT">
<source>Send%20Card</source>
</trans-unit>
<trans-unit id="105" resname="IDS_CARD_I_AM_DONE">
<source>I%20am%20Done</source>
</trans-unit>
<trans-unit id="106" resname="IDS_CARD_CANCEL">
<source>Go%20Back</source>
</trans-unit>
<trans-unit id="107" resname="IDS_CARD_SEND_ANOTHER_CARD">
<source>Send%20Another%20Card</source>
</trans-unit>
<trans-unit id="108" resname="IDS_CARD_SEND_EXPLANATION">
<source>Earn%20Neopoints%2A%20and%20send%20a%20card%20to%20your%20friends.%20%20They%20will%20be%20so%20happy%20to%20hear%20from%20you%20after%20so%20long%21</source>
</trans-unit>
<trans-unit id="109" resname="IDS_CARD_SEND_MAX_THREE_TIMES">
<source>%2AMax%203%20times%20daily.</source>
</trans-unit>
<trans-unit id="110" resname="IDS_PLAYEASY">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2715%27%3EPlay%20Game%20With%20BREAD%20%28Easy%29%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="111" resname="IDS_PLAYMED">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2715%27%3EPlay%20Game%20With%20STICK%20%28Medium%29%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="112" resname="IDS_LOCKEDMED">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2715%27%3ELOCKED%20need%20175m%20hit%21%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="113" resname="IDS_PLAYHARD">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2715%27%3EPlay%20Game%20With%20BAT%20%28Hard%29%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="114" resname="IDS_LOCKEDHARD">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2715%27%3ELOCKED%20need%20450m%20hit%21%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="115" resname="IDS_VIEWINSTRUCTIONS">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2715%27%3EView%20Instructions%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="116" resname="IDS_CLEARMARKERS">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2715%27%3EClear%20Markers%2F%20Farthest%20Whack%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="117" resname="IDS_INSTRUCTIONS">
<source>%3Cp%20align%3D%27left%27%3E%3Cfont%20size%20%3D%20%2712%27%3EObjective%3A%3Cbr%3E%20-%20Whack%20the%20Kass%20as%20far%20as%20you%20can%21%3Cbr%3E%3Cbr%3EHow%20To%20Play%3A%3Cbr%3E%20-%20Select%20the%20level%20of%20difficulty%3Cbr%3E%20-%20Click%20Left%20Mouse%20Button%20to%20drop%20Kass%3Cbr%3E%20-%20Click%20Left%20Mouse%20Button%20again%20to%20swing%20bat%3Cbr%3E%20-%20Spacebar%20may%20be%20used%20instead%20of%20mouse%3Cbr%3E%3Cbr%3EClear%20Markers%2F%20Furthest%20Whack%3A%3Cbr%3E%20-%20The%20game%20marks%20the%20spots%20where%20the%20Kass%20%3Cbr%3E%20has%20landed%20before.%20To%20Clear%20these%20marked%20%3Cbr%3E%20spots%20click%20on%20the%20Clear%20Markers%20button%20in%3Cbr%3E%20the%20main%20menu.%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="118" resname="IDS_BACK">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2715%27%3EBack%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="119" resname="IDS_RESTARTGAME">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2717%27%3ERestart%20Game%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="120" resname="IDS_SENDSCORE">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2717%27%3ESend%20Score%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="121" resname="IDS_HITAGAIN">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2715%27%3EClick%20anywhere%20to%20Whack%20Kass%20Again%21%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="122" resname="IDS_WIND">
<source>%3Cp%20align%3D%27left%27%3E%3Cfont%20size%20%3D%20%2714%27%20color%3D%27%23000000%27%3EWind</source>
</trans-unit>
<trans-unit id="123" resname="IDS_WINDMPH">
<source>meters%2Fsecond%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="124" resname="IDS_WINDNOHTML">
<source>Wind</source>
</trans-unit>
<trans-unit id="125" resname="IDS_TOPHIT">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20color%20%3D%20%27%23000000%27%20size%20%3D%20%2714%27%3EFarthest%20Whack%3A%20%3C%2Fp%3E%3C%2Ffont%3E</source>
</trans-unit>
<trans-unit id="126" resname="IDS_MARKERDISTANCE">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2712%27%3EDistance</source>
</trans-unit>
<trans-unit id="127" resname="IDS_MARKERMETERS">
<source>meters</source>
</trans-unit>
<trans-unit id="128" resname="IDS_MARKERDATE">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2712%27%3EDate</source>
</trans-unit>
<trans-unit id="129" resname="IDS_MARKERDAYOF">
<source>day%20of</source>
</trans-unit>
<trans-unit id="130" resname="IDS_NEWLEVEL">
<source>%3Cp%20align%3D%27center%27%3E%3Cfont%20size%20%3D%20%2724%27%3ENEW%20LEVEL%20UNLOCKED%21%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
<trans-unit id="131" resname="IDS_SLEEPING">
<source>Sleeping</source>
</trans-unit>
<trans-unit id="132" resname="IDS_AWAKENING">
<source>Awakening</source>
</trans-unit>
<trans-unit id="133" resname="IDS_RUNNING">
<source>Running</source>
</trans-unit>
<trans-unit id="134" resname="IDS_EATING">
<source>Eating</source>
</trans-unit>
<trans-unit id="135" resname="IDS_HUNTING">
<source>Hunting</source>
</trans-unit>
<trans-unit id="136" resname="IDS_RELAXING">
<source>Relaxing</source>
</trans-unit>
<trans-unit id="137" resname="IDS_SWIMMING">
<source>Swimming</source>
</trans-unit>
<trans-unit id="138" resname="IDS_HIDING">
<source>Hiding</source>
</trans-unit>
<trans-unit id="139" resname="IDS_GATHERING">
<source>Gathering</source>
</trans-unit>
<trans-unit id="140" resname="IDS_COLLECTING">
<source>Collecting</source>
</trans-unit>
<trans-unit id="141" resname="IDS_STORING">
<source>Storing</source>
</trans-unit>
<trans-unit id="142" resname="IDS_CELEBRATING">
<source>Celebrating</source>
</trans-unit>
<trans-unit id="143" resname="IDS_MAXHIT">
<source>%3Cp%20align%3D%27right%27%3E%3Cfont%20size%20%3D%20%2714%27%3EMaximum%20Hit%3C%2Ffont%3E%3C%2Fp%3E</source>
</trans-unit>
  </body>
  <system>
   <langs>
    <lang>
     <name>English</name>
     <code>en</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Nederlands</name>
     <code>nl</code>
     <enabled>0</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Portugu%C3%AAs</name>
     <code>pt</code>
     <enabled>0</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Deutsch</name>
     <code>de</code>
     <enabled>0</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Fran%C3%A7ais</name>
     <code>fr</code>
     <enabled>0</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Italiano</name>
     <code>it</code>
     <enabled>0</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>Espa%C3%B1ol</name>
     <code>es</code>
     <enabled>1</enabled>
     <langgroup>WE</langgroup>
    </lang>
    <lang>
     <name>%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87</name>
     <code>ch</code>
     <enabled>0</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87</name>
     <code>zh</code>
     <enabled>0</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%E6%97%A5%E6%9C%AC%E8%AA%9E</name>
     <code>ja</code>
     <enabled>0</enabled>
     <langgroup>NW</langgroup>
    </lang>
    <lang>
     <name>%ED%95%9C%EA%B5%AD%EC%96%B4</name>
     <code>ko</code>
     <enabled>0</enabled>
     <langgroup>NW</langgroup>
    </lang>
   </langs>
  </system>
 </file>
</xliff>
